### ISSUE TITLE
fumapress v1 build is not working without waku as devDependency

### ISSUE THREAD

**Issue by jvdwijngaard** [fuma-nama/fumapress#78]
After migrating to v1 and removing waku from the dependencies, `fumapress build` is not working.
Same for new projects created following the manual steps.

`npm run build` results in the following error:

```
[ssg] processing static generation...
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\projects\fumapress\client\dist\server\build.js' imported from C:\projects\fumapress\client\node_modules\waku\dist\lib\vite-plugins\static-build.js
    at finalizeResolution (node:internal/modules/esm/resolve:271:11)
    at moduleResolve (node:internal/modules/esm/resolve:865:10)
    at defaultResolve (node:internal/modules/esm/resolve:992:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:701:20)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:721:38)
    at nextStep (node:internal/modules/customization_hooks:189:26)
    at customizationHookResolve (file:///C:/projects/fumapress/client/node_modules/vite/dist/node/module-runner.js:1047:9)
    at nextStep (node:internal/modules/customization_hooks:189:26)
    at Ie (file:///C:/projects/fumapress/client/node_modules/@tailwindcss/node/dist/index.mjs:1:539)
    at nextStep (node:internal/modules/customization_hooks:189:26) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/projects/fumapress/client/dist/server/build.js'
}
```

After re-adding waku as a devDependency, it is working again.

Sidenote (not related to this item but maybe interesting to know): `npm create fumapress` generates pre v1 project with older versions of fumapress and its dependencies.

**Comment by fuma-nama** [comment]
would you mind to provide a reproduction?

**Comment by fuma-nama** [comment]
I think it's likely caused by missing `type: module` in package.json, Vite generates the server output differently for ESM and CJS. Although without the reproduction, I can't be sure.

**Comment by jvdwijngaard** [comment]
> I think it's likely caused by missing `type: module` in package.json, Vite generates the server output differently for ESM and CJS. Although without the reproduction, I can't be sure.

That might well be the case. I've simply followed the manual steps (https://press.fumadocs.dev/docs#manual-installation) and then run build. It probably is missing `type: module`.

Will check when I'm back and let you know. Thanks for pointing it out.

This will probably not be an issue when using `npm create fumapress`, but as mentioned the generated sources seem outdated (not v1).

**Comment by fuma-nama** [comment]
CLI should be updated now
